# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eb359aff209e357bae4c89bff59c7ebe96cfd22ff708a8e2a92b1389a446830dc1c809ea31e1fd5d31f957624614b280740933a4160d2c516b2e2737b0e099e

test:
  secret_key_base: 4936ec5f42360fb90066f3c4e44c7a25f15d8e20440ba4337b554bb871ff42d799844e47bb5281dfab7b37d3df9af4d46654b6ec866b91f376aa328af4b0acf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
